services:
  - type: web
    name: employee-project
    runtime: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
    startCommand: >
      python manage.py migrate --noinput &&
      python manage.py shell -c "
      from employees.models import Employee;
      import os;
      from django.core.management import call_command;
      if not Employee.objects.exists():
          print('ðŸŒ± First deploy detected â€” running seed_data...');
          call_command('seed_data');
      else:
          print('âœ… Existing data found â€” skipping seeding.');
      " &&
        gunicorn employee_project.wsgi:application --workers=2 --threads=4 --timeout=120 --bind 0.0.0.0:$PORT


    autoDeploy: true
    healthCheckPath: /health
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: ".onrender.com,localhost,127.0.0.1"
      - key: DJANGO_SETTINGS_MODULE
        value: "employee_project.settings"
      - key: DATABASE_URL
        fromDatabase:
          name: employee-db
          property: connectionString

databases:
  - name: employee-db
    plan: free
